import { getDefaultIndex } from '@/features/timeline/filters';

export const buildColumnProps = ({
  filter,
  index,
  filters,
  roomTags,
  isMobile,
  timelineFontFamily,
  timelineFontSize,
  animatingItemsColumn,
  animationEnabled,
  isGuestRulesAgreed,
  hideReply,
  hideInfo,
  localSpeech,
  localTagIds,
  localTagOperator,
  globalConditions,
  globalShowRange,
  focusedPostId,
  isGuestReactionOnly,
  showExternalShareButton,
  isSpeechActive,
}) => ({
  index,
  filter,
  isDefaultColumn: index === getDefaultIndex(filters),
  posts: Array.isArray(filter.posts) ? filter.posts : [],
  roomTags,
  isMobile,
  timelineFontFamily,
  timelineFontSize,
  isSpeechActive: isSpeechActive(filters, index),
  animatingItemsColumn,
  animationEnabled,
  isGuestRulesAgreed,
  hideReply,
  hideInfo,
  localSpeech,
  localTagIds,
  localTagOperator,
  globalConditions: globalConditions || null,
  globalShowRange: globalShowRange || null,
  focusedPostId,
  isGuestReactionOnly,
  showExternalShareButton,
});

export const buildColumnEvents = (commands) =>
  Object.freeze({
    onPressNotification: commands.onPressNotification,
    onGetNextPosts: commands.onGetNextPosts,

    showEditReplyDialog: commands.showEditReplyDialog,
    showDeleteReplyDialog: commands.showDeleteReplyDialog,
    showEditSupplementDialog: commands.showEditSupplementDialog,
    showDeleteSupplementDialog: commands.showDeleteSupplementDialog,
    showEditTagDialog: commands.showEditTagDialog,
    showGalleryDialog: commands.showGalleryDialog,
    showEditKickedUserDialog: commands.showEditKickedUserDialog,
    showDeletePostDialog: commands.showDeletePostDialog,
    showEditPostDialog: commands.showEditPostDialog,

    toggleColumnSpeech: commands.toggleColumnSpeech,
    showFilterDialog: commands.showFilterDialog,
    deleteFilter: commands.deleteFilter,
    successCreateFilter: commands.successCreateFilter,

    toggleAnimation: commands.toggleAnimation,
  });
