import { createCapabilitiesState } from './root/capabilities.js';

export const createRootState = () => ({
  capabilities: createCapabilitiesState(),
  user: {
    id: null,
    role: null,
    name: null,
    imageName: null,
    token: null,
    isLogin: false,
    guestId: null,
    guestName: null,
    guestToken: null,
    lang: null,
    eyeFriendlyMode: false,
    pushEnabled: false,
    replyPushEnabled: true,
    repliedPostPushEnabled: true,
  },
  floor: { id: null, title: null, targetLangs: null },
  room: { id: null, title: null, memberOnly: false, role: null },
  tag: { list: [] },
  tagClipboard: { list: [] },
  guestCache: { guestId: null, guestName: null, guestLang: null, guestToken: null },
  setting: {
    speechSpeed: 1,
    displayName: true,
    displayDate: true,
    displayTag: true,
    displaySupplement: true,
    displayActionButton: true,
    enableTextAnimation: true,
    animationSpeed: 'normal',
    displayUserKickButton: true,
  },
  ariahidden: { appToolbar: false, appMenu: true, appView: false },
  inertAppContainer: false,
  error: { message: null },
  guestSoundTags: [],
  filters: {},
  tempRoomId: null,
  message: {
    politeMessage: '',
    assertiveMessage: '',
    snackbarVisible: false,
    snackbarMessage: '',
    snackbarPosition: 'center',
    snackbarDuration: 3000,
    snackbarIsInfinity: false,
  },
});
